config/routes.rb
Rails.application.routes.draw do
  get 'users/new'

  get 'tasks' => 'tasks#index'
  root 'tasks#index'
  get 'signup'  => 'users#new' 
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  resources :tasks
  resources :users
  patch '/' => 'tasks#mark_done'

end

app/models/task.rb
class Task < ActiveRecord::Base
	belongs_to :user
	validates :title, presence: true
	validates :notes, presence: true
	validates :priority, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password
	has_many :tasks
	validates :first_name, presence: true
	validates :last_name, presence: true
	validates :email, presence: true
	validates :password, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user 

def current_user 
  @current_user ||= User.find(session[:user_id]) if session[:user_id] 
end

def require_user 
  redirect_to '/login' unless current_user 
end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new 
	end

	def create
  		@user = User.find_by_email(params[:session][:email])
  		if @user && @user.authenticate(params[:session][:password])
    		session[:user_id] = @user.id
    		redirect_to '/'
  		else
    		redirect_to 'login'
 		 end 
	end

	def destroy 
		session[:user_id] = nil 
		redirect_to '/' 
	end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  before_action :require_user, only: [:index, :show, :destroy, :mark_done]

  def index
    @user = current_user
    @tasks = Task.all
    @new_task = Task.new
  end

  def create
    @new_task = Task.create(task_params)
    @new_task.user_id = current_user.id
    if @new_task.save
    redirect_to '/'
  else
    redirect_to '/'
  end
end
  def destroy
  @ntask = Task.find(params[:id])
  if @ntask.destroy
    redirect_to '/'
  else
    redirect_to '/'

end
end

  def edit
    @update_task = Task.find(params[:id])
  end
  def update
    @task = Task.find(params[:id])
    @task.update
  end

  def mark_done
    @task_done = Task.find(params[:id])
    @task_done.status = "1"
    @task_done.save
    redirect_to '/'
  end
 
  private
    def task_params
      params.require(:task).permit(:title, :notes, :priority, :due)
    end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  	@user = User.new
  end

  def create
  	@user = User.new(user_params)
  	if @user.save
  		session[:usr_id] = @user.id
  		redirect_to '/'
  	else
  		redirect_to '/signup'
  	end
  end

	private
  	def user_params
   	 params.require(:user).permit(:first_name, :last_name, :email, :password)
  	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

  <title>TaskHelper | Increase Your Productivity</title>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.0/css/materialize.min.css">
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

</head>

<body class="blue darken-1">

	  <!-- Dropdown Structure -->
    <ul id="dropdown1" class="dropdown-content">

      <li><%= link_to "All Tasks", root_path, class: "blue-text" %></li>
      <li><a href="#modal1" class="modal-trigger blue-text">New Task</a></li>
      <li><a href="#!" class="blue-text">Account Settings</a></li>
      <li class="divider"></li>
      <li><%= link_to "Log out", logout_path, method: "delete", class: "amber-text text-darken-2" %></li>

    </ul>

<div class="navbar-fixed">
  <nav class="white">

    <div class="nav-wrapper">

      <%= link_to "Tasker", root_path, class: "brand-logo blue-text" %>

      <ul class="right hide-on-med-and-down">

        <li><a href="#" class="waves-effect waves-light blue-text">View Calendar</a></li>

        <!-- Dropdown Trigger -->
       
      	<% if current_user %> 
      		<li><a class="dropdown-button waves-effect waves-light blue-text" href="#!" data-activates="dropdown1">Welcome <%= current_user.first_name %><i class="material-icons right">arrow_drop_down</i></a></li>
      	<% else %>
      		<li><%= link_to "SignUp", signup_path, class: "waves-effect waves-light blue-text" %></li> 
      		<li><%= link_to "Login", login_path, class: "waves-effect waves-light blue-text" %></li>
      	<% end %>
      		
    </ul>
  </div>
</nav>
</div>
  
  

<%= yield %>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.0/js/materialize.min.js"></script>
<script>$(".dropdown-button").dropdown();
  $(document).ready(function(){
    // the "href" attribute of .modal-trigger must specify the modal ID that wants to be triggered
    $('.modal-trigger').leanModal();
  });
</script>

</body>
</html>

app/views/tasks/_new_task.html.erb
<div id="modal1" class="modal">
    <div class="modal-content container">
    	<div class="row">
      <%= form_for(@new_task, :html => { :class => 'col s12' }) do |f| %>
      	<div class="input-field col s6">
    	<%= f.label :title %>
   		 <%= f.text_field :title %>
   		</div>
   	

  		<div class="input-field col s6 ">
  		 
   		 <%= f.select :priority do %>
   		 <option value="" disabled selected>Set Task Priority</option>
  		<% [['Low', 1], ['Medium', 2], ['High', 3]].each do |c| -%>
   		 <%= content_tag(:option, c.first, value: c.last) %>
 		 <% end %>
		<% end %>
		
    	</div>
		</div>
		<div class="row">
			<div class="col s6 input-field">
    <%= f.label :notes %>
    <%= f.text_area :notes , class: "materialize-textarea", length: "150" %>
  </div>
  	<div class="input-field col s6">
    	<%= f.label :due, value: "Set a Target Date" %></br></br>
   		 <%= f.text_field :due, class: "datepicker" %>
   		</div>
	</div>
        <button class="waves-effect center-align waves-light btn-large blue darken-1" type="submit" name="commit">Create Task<i class="material-icons small right">flight_takeoff</i></button>


<% end %>
    </div>
  </div>

app/views/tasks/_task_number.html.erb
<% if @user.tasks.count == 0 %>
	<span>No Tasks to show. You're All Done!</span>
<% else %>
	<% if @user.tasks.count == 1 %>
			<span>1 Task</span>
	<% else %>
		<span><%= @user.tasks.count %> Tasks</span>
	<% end %>
<% end %>

app/views/tasks/index.html.erb
<!-- Number of Tasks -->

<div class="row">
  <div class="col s12 center-align white-text">
    <h5 class="flow-text "><%= render 'task_number' %></h5>
      <span class="new-badge padded red  white-text hoverable "><%= @user.tasks.where(priority: "3").count %> high</span>
      <span class="new-badge padded amber darken-2 white-text hoverable "><%= @user.tasks.where(priority: "2").count %> medium</span>
      <span class="new-badge padded light-green white-text hoverable "><%= @user.tasks.where(priority: "1").count %> low</span>
  </div>
</div>

<!-- end -->

<!-- Start listing tasks -->
  
<div class="row">
  <div class="col s4 m12 l10 offset-l1">
<% @user.tasks.each do |task| %>
	     
        <div class="col s4 m12 l4">

        	<% if task.priority == "1" %>
              <div class="card height_fixed hoverable low-p ">
            <% elsif task.priority == "2" %>
            	<div class="card height_fixed hoverable medium-p">
            <% elsif task.priority == "3" %>
            	<div class="card height_fixed hoverable high-p">
            <% else %>
              <div class="card height_fixed hoverable ">
            <% end %>

            <span class="card-title smaller "><i class="material-icons card-close tooltipped grey-text text-lighten-3" data-position="top" data-delay="10"  data-tooltip="Mark done!">done_all</i></span>

            <div class="card-content activator">
              <span class="card-title grey-text text-darken-4"><%= task.title %></span>
              <p><%= task.notes %></p>
            </div>

            <div class="card-footer  blue darken-4">
              <a class="waves-effect waves-light lighten-2 btn-flat btn-small activator white-text">Notes</a>
              <%= link_to 'Edit', edit_task_path(task), class: "modal-trigger waves-effect waves-light lighten-2 btn-flat btn-small  white-text " %>
              <span class="white-text"><%= task.due %></span>
            </div>

            <div class="card-reveal  blue darken-4 activator">
            	<div class="card-reveal-content">
            	 <span class="card-title smaller"><%= task.notes %><i class="material-icons card-close">close</i></span>
              </div>
            </div>
          </div>
        </div>

<% end %>
  </div>
</div>      

<%= render 'new_task' %>


  <% if @tasks.count != 0 %>
  <div class="fixed-action-btn" style="bottom: 45px; right: 24px;">
    <a class="btn-floating waves-effect waves-light btn-large blue darken-4 modal-trigger tooltipped" data-position="left" data-delay="10" data-tooltip="New Task" href="#modal1" >
      <i class="large material-icons">note_add</i>
    </a>
  </div>
  <% end %>
  <div class="number"><%= User.count %></div>


</div>
<script>
  $(document).ready(function() {
    $('select').material_select();

    $('.datepicker').pickadate({
    selectMonths: true, // Creates a dropdown to control month
    selectYears: 15, // Creates a dropdown of 15 years to control year
    formatSubmit: 'dd/mm/yyyy'
  });
  });


  </script>

app/views/tasks/show.html.erb
<h1>Tasks#show</h1>
<p>Find me in app/views/tasks/show.html.erb</p>

app/views/users/new.html.erb
  <div class="row">
    <div class="card col s6 offset-s3 top-margin hoverable signup-form">
        <%= form_for(@user, :html => { :class => 'col s10 offset-s1' }) do |f| %> 
        <div class="input-field col s6">
              <%= f.label :first_name %>
              <%= f.text_field :first_name %> 
        </div>
        <div class="input-field col s6">
          <%= f.label :last_name %>
          <%= f.text_field :last_name %>
        </div>
      
      
      <div class="row">
        <div class="input-field col s12">
          <%= f.label :email %>
          <%= f.email_field :email %> 
        </div>
      </div>

      <div class="row">
        <div class="input-field col s12">
          <%= f.label :password %>
          <%= f.password_field :password %>
        </div>
      </div>
      <div id="row">
        <div class="col s10 offset-1">
        <button class="waves-effect center-align waves-light btn-large blue darken-1" type="submit" name="commit">Launch<i class="material-icons small right">flight_takeoff</i></button>
    </div>
  </div>
    </form>
    <% end %>
    </div>
  </div>
  </div>